/**
 * Extract numeric timestamp from an ID or date string.
 * IDs generated by createLocalId / generateId look like "001742672072000-abc123".
 * For UUIDs or non-matching patterns, return 0 so they sort to the bottom (oldest).
 */
function extractTimestamp(id: string): number {
  if (!id) return 0;
  const match = id.match(/^(\d{13,15})-/);
  if (match) {
    return parseInt(match[1], 10);
  }
  // Try plain numeric prefix (e.g. "1742672072000")
  const numMatch = id.match(/^(\d{13,})/);
  if (numMatch) {
    return parseInt(numMatch[1], 10);
  }
  return 0;
}

/** Try to parse a date-like value into a numeric timestamp for sorting. */
function parseDateValue(val: string | undefined | null): number {
  if (!val) return 0;
  const t = Date.parse(val);
  return isNaN(t) ? 0 : t;
}

/**
 * Sort items so that the newest (highest timestamp) appear FIRST (index 0 → top of page)
 * and the oldest appear LAST (bottom of page, near the 2026 footer).
 * Uses `date` or `created_at` as fallback when IDs are UUIDs.
 */
export function sortByNewest<T extends { id: string; date?: string; created_at?: string }>(items: T[]): T[] {
  return [...items].sort((a, b) => {
    const tsA = extractTimestamp(a.id) || parseDateValue(a.date) || parseDateValue(a.created_at);
    const tsB = extractTimestamp(b.id) || parseDateValue(b.date) || parseDateValue(b.created_at);
    return tsB - tsA;
  });
}
